<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-04-07 17:52

$extensionClassesPath = t3lib_extMgm::extPath('extbase_pager') . 'Classes/';
return array(
	'tx_extbasepager_utility_pager' => $extensionClassesPath . 'Utility/Pager.php',
	'tx_extbase_viewhelpers_pagerviewhelper' => $extensionClassesPath . 'ViewHelpers/PagerViewHelper.php',
);
?>